# Site wide configuration

title:            Randomness of Josh Price
locale:           en_US
url:              http://jprice.github.io
version:        0.1.3


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Josh Price
  avatar: bio-photo.jpg
  bio: "Describe your self."
  email: josh@joshprice.net
  disqus-shortname: randomnessofjoshprice
  twitter: jpric3
  facebook: jpric3
  google:
    plus: #username
    analytics: UA-49914648-1
    verify: 0aR5_0pzt9ZyTTG0ZU6TMoOI_V1eY28fqDxwIftV_Ig
    ad-client:
    ad-slot:
  bing-verify: 30E07C7772DE6A58D16B60A75A292A4A
  github: jprice
  stackoverflow: 1657528/josh-price
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
