# General Jekyll Config
highlighter: pygments
url: http://outlaw.pw
lsi: false
disqus-shortname: randomnessofjoshprice
include: [".htaccess"]
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
